name: Access GitHub Secrets

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  access-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Print Secrets
        env:
          SPOTIFY_SECRET: ${{ secrets.SPOTIFY_SECRET }} 
          SPOTIFY_ID: ${{ secrets.SPOTIFY_ID }}
        run: |
          echo "Secrets available"


