name: Access GitHub Secrets

on:
  push:
    branches:
      - main

jobs:
  access-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Access Secrets
        env:
          SPOTIFY_SECRET: ${{ secrets.SPOTIFY_SECRET }} 
          SPOTIFY_ID: ${{ secrets.SPOTIFY_ID }}
        run: |
          echo "MY_SECRET: $MY_SECRET"
          echo "ANOTHER_SECRET: $ANOTHER_SECRET"
